name: Auto Pull Request prod

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions: write-all

jobs:
  auto-pull-request-prod:
    strategy:
      matrix:
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Create pull request but not if develop
        run: |
          if ! gh pr list -B main | grep OPEN; then
            gh pr create \
              --head develop \
              --base main \
              --title "Deploy to Release 🎉" \
              --body "Deploy to Release 🎉"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: naohito-T/gh-actions-changeset-commenter@main
        name: Add branch comment
        with:
          base: main
